### ISSUE TITLE
[1.18.2] Crash When Clicking An Effect

### ISSUE THREAD

**Issue by Phweeeee** [MehVahdJukaar/JustEnoughEffectDescriptions#22]
So I have a fairly large modpack and wanted to add Just Enough Effect Descriptions. Unfortunately. when I clicked an effect that I had on, It crashed my game. Below is the crash report.

Report: https://paste.gg/p/anonymous/06ad5b152a03403f8dae3f1e51b8759f

**Comment by MehVahdJukaar** [comment]
Seems either an outdated JEI or it recently got updated changing the api

**Comment by Phweeeee** [comment]
I'm using the latest beta build of JEI for 1.18.2, which is 1.18.2-9.7.2.273

**Comment by Phweeeee** [comment]
Has this been looked into?

**Comment by MehVahdJukaar** [comment]
Not yet

**Comment by Not-February** [comment]
I'm having this occur on a 1.19.2 version of the mod as well in my modpack; it's not just 1.18.2. Might consider cross comparing mods which add innate JEED support to see if there's anything in common between our two modpacks?

[Crash log for my particular case](https://gist.github.com/Not-February/7100d9ed2afaf8405abf2783e80dc91fl)

(relevant versions of basic mods, though they're also in the log)
MC 1.19.2
Forge 43.2.1
JEI 11.5.0.297
JEED 1.17

**Comment by MehVahdJukaar** [comment]
Can you upload that log again?

**Comment by Not-February** [comment]
Oops. Guess I messed up the link somehow.

[Here you go.](https://gist.github.com/Not-February/7100d9ed2afaf8405abf2783e80dc91f)

**Comment by Lilygabe** [comment]
I hope this will be looked into soon, I am also having the same issue in 1.18.2

**Comment by Shadowrs** [comment]
Same issue for me. 
jeed-1.18.2-1.11
jei-1.18.2-forge-10.2.1.283
MC 1.18.2
Forge 40.2.0

https://pastebin.com/aBqjag7L

```
java.lang.NullPointerException: Cannot invoke "mezz.jei.api.runtime.IJeiRuntime.getRecipesGui()" because "net.mehvahdjukaar.jeed.jei.JEIPlugin.JEI_RUNTIME" is null
	at net.mehvahdjukaar.jeed.jei.plugins.InventoryScreenHandler.onClickedEffect(InventoryScreenHandler.java:73) ~[jeed-1.18.2-1.11.jar%23231!/:1.18.2-1.11] {re:mixin,re:classloading}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_6375_(EffectRenderingInventoryScreen.java:530) ~[client-1.18.2-20220404.173914-srg.jar%23409!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:jeed.mixins.json:DisplayEffectScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

**Comment by FanRenLa** [comment]
1.19.2
The same

**Comment by him126163** [comment]
it also crash in 1.18.1
[crash-2023-02-08_11.49.28-client.txt](https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions/files/10681550/crash-2023-02-08_11.49.28-client.txt)
so , if l install the jei in 2022.2 or earlier,it will crashed or not？

**Comment by Diedntgo** [comment]
Also having this issue in 1.18.2

jei-1.18.2-forge-10.2.1.1002
jeed-1.18.2-1.11

**Comment by MehVahdJukaar** [comment]
Still can't replicate

**Comment by MehVahdJukaar** [comment]
Maybe it's some other Jei plugin failing

**Comment by him126163** [comment]
no,i haven"t installed bontania yet

**Comment by Diedntgo** [comment]
You might have some other mod with the same issue Botania seems to have. For me, removing just Botania from my ~350 mods fixed the issue (1.18.2)

**Comment by MetalKnight56** [comment]
Yep can confirm, this is def an issue with botania and JEED

**Comment by thevalleyy** [comment]
This issue ist [still present](https://pastebin.com/jLgRAF8E) in 1.20.1.

**Comment by MehVahdJukaar** [comment]
Do you have jei or Rei I stalled?

**Comment by thevalleyy** [comment]
No. I've installed Better Recipe Book if that helps.

**Comment by TysonTheEmber** [comment]
I am also requesting a fix for this, or simply make a config to disable clicking on effect in inventory. https://pastebin.com/3UaxfvjK

**Comment by OliverWolf621** [comment]
Bump, still an issue on 1.18.2
